# Введение в анализ данных
## НИУ ВШЭ, 2019-2020 учебный год

### Домашнее задание №3

Задание выполнил(а): _Новиков Владимир_

### Общая информация

__Дата выдачи:__ 06.04.2020

__Дедлайн:__ 23:59 20.04.2020


### Оценивание и штрафы

Оценка за ДЗ вычисляется по следующей формуле:

$$
min(\text{points}, 18)  \times 10 / 18,
$$

где points — количество баллов за обязательную часть, которое вы набрали. Максимальное число баллов, которое можно получить за обязательную часть — 18, за каждые полтора балла сверху вы получите 1 бонусный балл (максимум 2). Также вы можете использовать бонусные баллы, которые накопили ранее.

За сдачу задания позже срока на итоговую оценку за задание накладывается штраф в размере 1 балл в день, но получить отрицательную оценку нельзя.

__Внимание!__ Домашнее задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов.

### Формат сдачи

Загрузка файлов с решениями происходит в системе [Anytask](https://anytask.org/).

Инвайт для группы ИАД-6: rd5CNrr

Перед отправкой перезагрузите ноутбук и проверьте, что все ячейки могут быть последовательно выполнены. Ноутбук должен запускаться с использованием python 3.6+

### Подготовка данных

In [0]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

from tqdm import tqdm

In [3]:
# Качаем датасет

!wget https://www.dropbox.com/s/tg55q9mrziroyrs/train_subset.csv

--2020-04-23 19:16:10--  https://www.dropbox.com/s/tg55q9mrziroyrs/train_subset.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.65.1, 2620:100:6021:1::a27d:4101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.65.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/tg55q9mrziroyrs/train_subset.csv [following]
--2020-04-23 19:16:11--  https://www.dropbox.com/s/raw/tg55q9mrziroyrs/train_subset.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc8b32eb6b3a81551b4dcf7a4ab2.dl.dropboxusercontent.com/cd/0/inline/A2ZOUsGwBLJIvygezjDTbLMPivG0MQI8vSoGCjbfGhK0w3TFemQXvs99HAGinoZnjuFnSzNILoN0C1qxXEAFCSHw0QCzlJrQz9JdPdqvIn8pLfY-M2jAsNYsf3Cy7pAMM1Q/file# [following]
--2020-04-23 19:16:11--  https://uc8b32eb6b3a81551b4dcf7a4ab2.dl.dropboxusercontent.com/cd/0/inline/A2ZOUsGwBLJIvygezjDTbLMPivG0MQI8vSoGCjbfGhK0w3TFemQXvs99HAGinoZnjuFnSzNILoN0C1qxXEAFCSHw0QCzlJrQz9J

### Данные

Мы имеем дело с данными с торговой платформы Avito.
Для каждого товара представлены следующие параметры:
 - title
 - description
 - Category_name
 - Category

Имеется информация об объектах 50 классов.
Задача: по новым объектам (title, description) предсказать Category.
(Очевидно, что параметр Category_name для предсказания классов использовать нельзя)

In [4]:
data = pd.read_csv("train_subset.csv", index_col='id')

data.head()

title  ... Category
id                                  ...         
382220                    Прихожая  ...       20
397529   Кордиант 215/55/16 Летние  ...       10
584569                        Стол  ...       20
2513100                 Комбинезон  ...       27
1091886                   Ветровка  ...       29

[5 rows x 4 columns]

In [5]:
data.shape

(30000, 4)

In [0]:
X = data[['title', 'description']].to_numpy()
y = data['Category'].to_numpy()

del data

Сразу разделим выборку на train и test.
Никакие данные из test для обучения использовать нельзя!

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [8]:
X_train[:5]

array([['Сапоги 46 размер новые', 'Сапоги 46 размер новые'],
       ['Светильники потолочный swarovski',
        'светильники потолочные swarovski 6 штук , цена за штуку. В эксплуатации 2 года , продаются в связи со сменой интерьера в квартире'],
       ['iPhone 7 plus 128GB Red красный в наличии',
        '\xa0/\n/\n Данная цена только для подписчиков Instagram: iQmac/\n/\n Новый красный айфон 7 Plus в наличии это элегантный и мощный смартфон, который готов в полной мере раскрыть новые возможности iOS 10. Аппарат с 4-ядерным процессором А10 и 3 ГБ ОЗУ с легкостью решает самые ресурсоемкие задачи, позволяя наслаждаться быстродействием «тяжелых» приложений и игр на 5,5-дюймовом дисплее. Аппарат получил экран, как у iPad Pro, так что картинка теперь соответствует кинематографическому стандарту.'],
       ['Пион Ирис Ромашка рассада',
        'Пион куст 500 р ( более 10 шт)/\nСаженец/ корень 100р/\nРастут у нас более 70 лет/\nРозовые, бордовые и белые/\nНа фото цветы 2018г/\nП. Зубчанинов

In [9]:
y_train[:5]

array([ 27,  20,  84, 106,  27])

### Токенизация (1 балл)


Токенизация -- разбиение текста на мелкие части, которые можно обработать машинными методами.
Можно использовать разные алгоритмы токенизации.
Можете использовать WordPunctTokenizer или подобрать какой-то другой, если считаете, что он лучше подойдет для этой задачи.


In [10]:
from nltk.tokenize import WordPunctTokenizer

tokenizer = WordPunctTokenizer()

text = 'Здраствуйте. Я, Кирилл. Хотел бы чтобы вы сделали игру, 3Д-экшон суть такова...'

print("before:", text,)
print("after:", tokenizer.tokenize(text.lower()),)

before: Здраствуйте. Я, Кирилл. Хотел бы чтобы вы сделали игру, 3Д-экшон суть такова...
after: ['здраствуйте', '.', 'я', ',', 'кирилл', '.', 'хотел', 'бы', 'чтобы', 'вы', 'сделали', 'игру', ',', '3д', '-', 'экшон', 'суть', 'такова', '...']


__Задание:__ реализуйте функцию ниже

In [0]:
def preprocess(text: str) -> str:
    """
    Данная функция принимает на вход текст, 
    а возвращает тот же текст, но с пробелами между каждым токеном
    """
    text = text.lower()
    return ' '.join(tokenizer.tokenize(text))

# your code here

In [12]:
print(preprocess(text))
assert preprocess(text) == 'здраствуйте . я , кирилл . хотел бы чтобы вы сделали игру , 3д - экшон суть такова ...'

здраствуйте . я , кирилл . хотел бы чтобы вы сделали игру , 3д - экшон суть такова ...


__Задание:__ токенизируйте title и description в train и test

In [0]:
for i, row in enumerate(X_train):
    for j, cell in enumerate(row):
        X_train[i][j] = preprocess(X_train[i][j])

for i, row in enumerate(X_test):
    for j, cell in enumerate(row):
        X_test[i][j] = preprocess(X_test[i][j])

In [14]:
print(X_train[10][1])
assert X_train[10][1] == 'продам иж планета 3 , 76 год , ( стоит на старом учёте , документы утеряны ) на ходу , хорошее состояние , все интересующие вопросы по телефону ( с родной коляской на 3 тысячи дороже ) . торга не будет .'

продам иж планета 3 , 76 год , ( стоит на старом учёте , документы утеряны ) на ходу , хорошее состояние , все интересующие вопросы по телефону ( с родной коляской на 3 тысячи дороже ) . торга не будет .


In [15]:
X_train

array([['сапоги 46 размер новые', 'сапоги 46 размер новые'],
       ['светильники потолочный swarovski',
        'светильники потолочные swarovski 6 штук , цена за штуку . в эксплуатации 2 года , продаются в связи со сменой интерьера в квартире'],
       ['iphone 7 plus 128gb red красный в наличии',
        '/ / данная цена только для подписчиков instagram : iqmac / / новый красный айфон 7 plus в наличии это элегантный и мощный смартфон , который готов в полной мере раскрыть новые возможности ios 10 . аппарат с 4 - ядерным процессором а10 и 3 гб озу с легкостью решает самые ресурсоемкие задачи , позволяя наслаждаться быстродействием « тяжелых » приложений и игр на 5 , 5 - дюймовом дисплее . аппарат получил экран , как у ipad pro , так что картинка теперь соответствует кинематографическому стандарту .'],
       ...,
       ['lada kalina , 2008',
        'всю информацию о кредитовании можно получить у сотрудников петровского автоцентра ./ / об автомобиле :/ - автомобиль приобретался у оф

### BOW (3 балла)

Один из традиционных подходов -- построение bag of words.

Метод состоит в следующем:

 - Составить словарь самых часто встречающихся слов в train data
 - Для каждого примера из train посчитать, сколько раз каждое слово из словаря в нём встречается


 В sklearn есть CountVectorizer, но в этом задании его использовать нельзя.

__Задание:__ создайте словарь, где в соответствии каждому токену стоит количество раз, которое оно встретилось в X_train

In [0]:
words_list = tokenizer.tokenize(' '.join(X_train.flatten()))
tokens = {}

for word in words_list:
    if word not in tokens.keys():
        tokens[word] = 1
    else:
        tokens[word] += 1

In [0]:
assert tokens['сапоги'] == 454

__Задание:__ выведите 10 самых частотных и 10 самых редких токенов

In [18]:
# your code here
for x in list(sorted(tokens.items(), key=lambda x: x[1]))[0:10]:
    print (x)
for x in list(sorted(tokens.items(), key=lambda x: x[1]))[-10:]:
    print (x)

('iqmac', 1)
('ядерным', 1)
('ресурсоемкие', 1)
('быстродействием', 1)
('кинематографическому', 1)
('ирис', 1)
('саженец', 1)
('корень', 1)
('зубчаниновка', 1)
('боярышник', 1)
('с', 12860)
(':', 15098)
('./', 17639)
('на', 19465)
('и', 21714)
('в', 28337)
('-', 36840)
('.', 65624)
(',', 79117)
('/', 85802)


__Задание:__ оставьте в словаре только топ 10000 самых частотных токенов

In [19]:
len(tokens)

94292

In [20]:
# your code here
import collections

c = collections.Counter(tokens)
print(c.most_common(10000))
most_common = c.most_common(10000)

[('/', 85802), (',', 79117), ('.', 65624), ('-', 36840), ('в', 28337), ('и', 21714), ('на', 19465), ('./', 17639), (':', 15098), ('с', 12860), ('(', 12157), ('по', 10000), ('для', 9627), ('не', 6045), (')', 5782), ('2', 5766), ('1', 5284), ('!', 5198), ('до', 4541), ('от', 4482), ('—', 4449), ('"', 4250), ('3', 4071), ('5', 4003), ('состоянии', 3981), ('!/', 3916), ('у', 3855), ('за', 3425), ('все', 3382), ('размер', 3320), ('без', 3258), ('из', 3137), ('*', 2944), ('4', 2939), ('есть', 2906), ('доставка', 2840), ('00', 2799), ('см', 2774), ('к', 2681), ('продам', 2677), ('состояние', 2666), ('или', 2631), (')/', 2471), ('10', 2452), ('цена', 2379), (':/', 2311), ('б', 2266), ('•', 2212), ('наличии', 2172), ('руб', 2147), ('6', 2126), ('при', 2111), ('очень', 2064), ('р', 1987), ('фото', 1978), ('новые', 1872), ('звоните', 1858), ('можно', 1855), ('м', 1853), ('запчасти', 1717), (';/', 1697), ('+', 1668), ('новый', 1626), ('8', 1609), ('отличном', 1577), ('20', 1551), ('7', 1485), ('пр

In [21]:
len(most_common)

10000

In [0]:
most_common = dict(most_common) 

In [23]:
isinstance(most_common, dict)

True

__Задание:__ реализуйте функцию, которая предложение переводит в вектор из чисел. То есть каждому слову из словаря сопоставляется количество раз, которое оно встретилось в предложении.

In [0]:
def text_to_bow(text: str, mc: dict) -> np.array:
    """
    Возвращает вектор, где для каждого слова из most_common
    указано количество его употреблений
    input: строка
    output: вектор размерности словаря
    """
    tkns = text.split()
    res = np.zeros(len(mc))
    tok = {}
    #print(tkns)
    
    for token in tkns:
        if token not in tok.keys():
            tok[token] = 1
        else:
            tok[token] += 1
    
    
    for token in range(len(tkns)):
        if tkns[token] in mc:        
            indx = list(mc.keys()).index(tkns[token])
            res[indx] = tok[tkns[token]]
        
    return res   

In [25]:
print(text_to_bow(preprocess('46, рублей, .. /'), most_common))

[1. 2. 0. ... 0. 0. 0.]


In [26]:
print(len(text_to_bow(preprocess('46, рублей, .. /'), most_common)))

10000


__Задание:__ а теперь реализуйте функцию, которая преобразует наш датасет и для каждого текста из description сопоставляет вектор.

In [27]:
print(X_train.shape)

(21000, 2)


In [0]:
def items_to_bow(items: np.array) -> np.array:
    """ Для каждого товара возвращает вектор его bow """
    # Давайте для начала попробуем строить bow только из description товара
    items = items[:, 1]
    res = np.zeros([len(items), 10000])
    for i, row in enumerate(items):
        res[i] = text_to_bow(str(items[i]), most_common)
        if i % 1000 == 0:
          print(i)

    return res
    # your code here

In [29]:
X_train_bow = items_to_bow(X_train)
X_test_bow = items_to_bow(X_test)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
0
1000
2000
3000
4000
5000
6000
7000
8000


In [0]:
print(X_train_bow)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  2.  1. ...  0.  0.  0.]
 [ 4.  5.  3. ...  0.  0.  0.]
 ...
 [42. 14.  4. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 1.  0.  4. ...  0.  0.  0.]]


In [0]:
# чтобы видеть проход по итерациям можно использовать библиотеку tqdm
# она работает примерно так
from tqdm import tqdm

for i in tqdm(range(100)):
    pass

100%|█████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 14325.30it/s]


In [0]:
from sklearn.metrics import accuracy_score

### Логистическая регрессия и SVC (0.5 балла)


Теперь описание каждого товара представлено, как точка в многомерном пространстве.
Очень важно запомнить эту идею: дальше мы будем рассматривать разные способы перехода от текста к точке в пространстве.

Для BOW каждое измерение в пространстве -- какое-то слово.
Мы предполагаем, что текст описывается набором каких-то популярных слов, которые в нём встречаются, а близкие по смыслу тексты будут использовать одинаковые слова.

Обучите логистическую регрессию и SVC с базовыми параметрами.


In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

In [0]:
lr_model = LogisticRegression()
lr_model.fit(X_train_bow, y_train)

print(accuracy_score(lr_model.predict(X_test_bow), y_test))
assert accuracy_score(lr_model.predict(X_test_bow), y_test) > 0.7

C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7046666666666667


In [0]:
svc_model = LinearSVC(C = 0.1, max_iter = 10000)
svc_model.fit(X_train_bow, y_train)

print(accuracy_score(svc_model.predict(X_test_bow), y_test))
assert accuracy_score(svc_model.predict(X_test_bow), y_test) > 0.68

0.7211111111111111


### Модификация признаков (0.5 балла)

Добавьте title товара в bow с произвольным весом, как изменится качество?

In [0]:
# Your code here
def title_to_bow(items: np.array) -> np.array:
    """ Для каждого товара возвращает вектор его bow """
    # Давайте для начала попробуем строить bow только из description товара
    items = items[:, 0]
    res = np.zeros([len(items), 10000])
    for i, row in enumerate(items):
        res[i] = text_to_bow(str(items[i]), most_common)

    return res

In [0]:
train_title_bow = title_to_bow(X_train)
test_title_bow = title_to_bow(X_test)

In [0]:
print(train_title_bow.ndim)

2


In [0]:
print(test_title_bow)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [0]:
xtrain_bow = np.add(5 * train_title_bow, X_train_bow)
xtest_bow = np.add(5 * test_title_bow, X_test_bow)

In [0]:
print(xtrain_bow.shape)

(21000, 10000)


In [0]:
lr_model.fit(xtrain_bow, y_train)

print(accuracy_score(lr_model.predict(xtest_bow), y_test))

C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7913333333333333


Мы видим, что качество логистической модели выросло после включения ```title```, однако это может являться следствием мультиколлинеарности и дублирования информации в train и test

In [0]:
svc_model.fit(xtrain_bow, y_train)

print(accuracy_score(svc_model.predict(xtest_bow), y_test))

0.7851111111111111


Тоже самое касается SVC модели, accuracy которой также увеличилось, однако данные все еще достаточно проблемные и надо почистить их от знаков препинания и стоп-слов.

Нормализуйте данные (`sklearn.preprocessing.normalize`) перед обучением. Что станет с качеством и почему?

In [0]:
# Your code here
from sklearn.preprocessing import normalize
xtrain_norm = normalize(X_train_bow)

xtest_norm = normalize(X_test_bow)

In [0]:
print(xtest_norm)

[[0.58520574 0.05852057 0.35112344 ... 0.         0.         0.        ]
 [0.         0.2773501  0.2773501  ... 0.         0.         0.        ]
 [0.71795816 0.07179582 0.14359163 ... 0.         0.         0.        ]
 ...
 [0.60192927 0.06019293 0.18057878 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.54173634 0.54173634 ... 0.         0.         0.        ]]


In [0]:
lr_model.fit(xtrain_norm, y_train)

print(accuracy_score(lr_model.predict(xtest_norm), y_test))

C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.5833333333333334


In [0]:
svc_model.fit(xtrain_norm, y_train)

print(accuracy_score(svc_model.predict(xtest_norm), y_test))

0.6348888888888888


Нормализация данных неожиданно ухудшила ```accuracy``` модели (это может быть связано с тем, что ```y``` не нормирован, так как это категориальная переменная), но зато значительно увеличилась скорость расчета SVC-модели

### Mystem (1 балл)

Попробуйте обучиться, используя токенизатор mystem. Сравните качество.

In [0]:
!wget http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz
!tar -xvf mystem-3.0-linux3.1-64bit.tar.gz
!cp mystem /bin

--2020-04-23 08:22:43--  http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz
Resolving download.cdn.yandex.net (download.cdn.yandex.net)... 5.45.205.242, 5.45.205.245, 5.45.205.244, ...
Connecting to download.cdn.yandex.net (download.cdn.yandex.net)|5.45.205.242|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://cache-mskm907.cdn.yandex.net/download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz [following]
--2020-04-23 08:22:43--  http://cache-mskm907.cdn.yandex.net/download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz
Resolving cache-mskm907.cdn.yandex.net (cache-mskm907.cdn.yandex.net)... 5.45.220.17, 2a02:6b8:0:2002::18
Connecting to cache-mskm907.cdn.yandex.net (cache-mskm907.cdn.yandex.net)|5.45.220.17|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16457938 (16M) [application/octet-stream]
Saving to: ‘mystem-3.0-linux3.1-64bit.tar.gz.1’

mystem-3.0-linux3.1 100%[===================>] 

In [0]:
pip install git+https://github.com/nlpub/pymystem3

  Cloning https://github.com/nlpub/pymystem3 to /tmp/pip-req-build-umacq8_b
  Running command git clone -q https://github.com/nlpub/pymystem3 /tmp/pip-req-build-umacq8_b
  Created wheel for pymystem3: filename=pymystem3-0.2.0-cp36-none-any.whl size=9921 sha256=e34c76ebe39f7b8770bc1f9e6c97d20d7807d50afb68f3aa9c75ffd8bdc51ab2
  Stored in directory: /tmp/pip-ephem-wheel-cache-q2ao8cy7/wheels/7d/75/c2/216a594291dee680749ce12c60d16125cfe1f363059e7163dc
Successfully built pymystem3


In [0]:
from pymystem3 import Mystem
mystem_analyzer = Mystem()

In [0]:
mystem_analyzer.lemmatize("Попробуйте обучиться, используя токенизатор mystem. Сравните качество.")

['попробовать',
 ' ',
 'обучаться',
 ', ',
 'использовать',
 ' ',
 'токенизатор',
 ' ',
 'mystem',
 '. ',
 'сравнивать',
 ' ',
 'качество',
 '.',
 '\n']

In [0]:
from sklearn.model_selection import train_test_split

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X, y, test_size=0.3, random_state=42)

In [0]:
for i, row in enumerate(X_train_m):
    for j, cell in enumerate(row):
        X_train_m[i][j] = ''.join(mystem_analyzer.lemmatize(X_train_m[i][j]))
    if i % 5000 == 0:
        print(i)

0
5000
10000
15000
20000


In [0]:
print(X_train_m)

[['сапог 46 размер новый\n' 'сапог 46 размер новый\n']
 ['светильник потолочный swarovski\n'
  'светильник потолочный swarovski 6 штука , цена за штука. в эксплуатация 2 год , продаваться в связь со смена интерьер в квартира\n']
 ['iPhone 7 plus 128GB Red красный в наличие\n'
  '\xa0/\n/\n данный цена только для подписчик Instagram: iQmac/\n/\n новый красный айфон 7 Plus в наличие это элегантный и мощный смартфон, который готовый в полный мера раскрывать новый возможность iOS 10. аппарат с 4-ядерный процессор А10 и 3 гб озу с легкость решать самый ресурсоемкий задача, позволять наслаждаться быстродействие «тяжелый» приложение и игра на 5,5-дюймовый дисплей. аппарат получать экран, как у iPad Pro, так что картинка теперь соответствовать кинематографический стандарт.\n']
 ...
 ['LADA Kalina, 2008\n'
  'весь информация о кредитование можно получать у сотрудник петровский автоцентр./\n/\nоб автомобиль:/\n- автомобиль приобретаться у официальный дилер/\n- 2 хозяин/\n- оригинал ПТС/\n- полны

In [0]:
for i, row in enumerate(X_test_m):
    for j, cell in enumerate(row):
        X_test_m[i][j] = ''.join(mystem_analyzer.lemmatize(X_test_m[i][j]))
    if i % 2000 == 0:
       print(i)

0
2000
4000
6000
8000


In [0]:
print(X_test_m)

[['винт сдвижной панель потолок бмв Х5 Е53\n'
  '"*3308* винт сдвижной панель потолок oem: 54107199476 (54 10 7 199 476) /\n/\n запчасть б/у в хороший состояние для BMW X5 E53, /\nдемонтировать с автомобиль из япония без пробег по рф. гарантия на весь запчасть 14 день. возможный замена/установка в автосервис партнер. /\nпримечание: / /\nдля упрощение поиск запчасть сообщать мы внутренний код: *3308* /\nв наличие на склад: 16 шт. /\nпроверять соответствие данный запчасть по оригинальный номер оем - ваш автомобиль по VIN. более 1000 наименование запасной часть для BMW на наш склад в москва. отправлять по весь россия почта или транспортный компания"\n']
 ['сандалик Totto для мальчик\n'
  'продавать сандалик Totto для малыш! размер 20,по стелька 12 см.\n']
 ['фара правый Toyota RAV 4 галоген 2015-19\n'
  'фара  правый  для  Toyota  RAV4   2015/\nоригинальный номер: 8113042650/\nтойота рав4 тоета рав 4/\nпроизводитель: Toyota/\nсостояние: отличный без дефект ! /\nкомментарий: после 2015 не 

Далее используем написанные ранее функции, применив их к данной токенизации:

In [0]:
words_list_m = mystem_analyzer.lemmatize(' '.join(X_train_m.flatten()))
tokens_m = {}

for word in words_list_m:
    if word not in tokens_m.keys():
        tokens_m[word] = 1
    else:
        tokens_m[word] += 1

In [0]:
print(len(tokens_m))

64451


In [0]:
import collections

c = collections.Counter(tokens_m)
most_common_m = c.most_common(10000)

In [0]:
len(most_common_m)

10000

In [0]:
most_common_m = dict(most_common_m) 

In [0]:
isinstance(most_common_m, dict)

True

In [0]:
def items_to_bow_m(items: np.array) -> np.array:
    """ Для каждого товара возвращает вектор его bow """
    # Давайте для начала попробуем строить bow только из description товара
    items = items[:, 1]
    res = np.zeros([len(items), 10000])
    for i, row in enumerate(items):
        res[i] = text_to_bow(str(items[i]), most_common_m)
        if i % 1000 == 0:
          print(i)
    return res

In [0]:
X_train_bow_m = items_to_bow_m(X_train_m)
X_test_bow_m = items_to_bow_m(X_test_m)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
0
1000
2000
3000
4000
5000
6000
7000
8000


In [0]:
lr_model = LogisticRegression(max_iter=5000)
lr_model.fit(X_train_bow_m, y_train_m)

print(accuracy_score(lr_model.predict(X_test_bow_m), y_test_m))

0.6766666666666666


In [0]:
svc_model = LinearSVC(C = 0.1, max_iter = 10000)
svc_model.fit(X_train_bow_m, y_train_m)

print(accuracy_score(svc_model.predict(X_test_bow_m), y_test_m))

0.6907777777777778


Мы видим, что результаты незначительно ухудшились, по сравнению с моделями, построенными на другом токенизаторе, однако сложно дать однозначный ответ о причинах этого: возможно тот факт, что я не избавился от пунктуации и стоп-слов сильнее сказывается на качестве моделей, если в выборке меньше шума (то есть проведена лемматизация)

### TF-IDF (5 баллов)

Не все слова полезны одинаково, давайте попробуем [взвесить](http://tfidf.com/) их, чтобы отобрать более полезные.


> TF(t) = (Number of times term t appears in a document) / (Total number of terms in the document).
> 
> IDF(t) = log_e(Total number of documents / Number of documents with term t in it).


В sklearn есть TfidfVectorizer, но в этом задании его использовать нельзя. Для простоты посчитайте общий tf-idf для title и description (то есть каждому объекту надо сопоставить вектор, где как документ будет рассматриваться конкатенация title и description).

__Задание:__ составьте словарь, где каждому слову из изначального словаря будет стоять в соответствии количество документов, где это слово встретилось.

In [0]:
# your code here
docswterm = {}

def termdocdict(dat):
    
    for i, row in enumerate(dat):
        dat2str = str(dat[i][0]) + " " + str(dat[i][1]) #str(dat[i])
        tkns_list = tokenizer.tokenize(dat2str)


        #print(str(dat[i]))
        tkns = {}

        for token in tkns_list:
            tkns[token] = 1
                
        for token in tkns.keys():
            if token not in docswterm.keys():
                docswterm[token] = 1
            else:
                docswterm[token] += 1
        
        if i % 1000 == 0:
          print(i)

    return docswterm

In [0]:
docswterm = termdocdict(X_train)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000


In [0]:
print(docswterm)

{'сапоги': 285, '46': 391, 'размер': 2839, 'новые': 1519, 'светильники': 20, 'потолочный': 6, 'swarovski': 7, 'потолочные': 8, '6': 1548, 'штук': 112, ',': 14630, 'цена': 2041, 'за': 2802, 'штуку': 125, '.': 15735, 'в': 11893, 'эксплуатации': 147, '2': 3529, 'года': 882, 'продаются': 146, 'связи': 308, 'со': 782, 'сменой': 10, 'интерьера': 38, 'квартире': 210, 'iphone': 221, '7': 1155, 'plus': 92, '128gb': 24, 'red': 27, 'красный': 106, 'наличии': 1814, '/': 9320, 'данная': 148, 'только': 986, 'для': 5534, 'подписчиков': 2, 'instagram': 39, ':': 4341, 'iqmac': 1, 'новый': 1385, 'айфон': 32, 'это': 607, 'элегантный': 13, 'и': 8355, 'мощный': 47, 'смартфон': 47, 'который': 182, 'готов': 79, 'полной': 69, 'мере': 8, 'раскрыть': 3, 'возможности': 67, 'ios': 33, '10': 1827, 'аппарат': 56, 'с': 6746, '4': 2054, '-': 9581, 'ядерным': 1, 'процессором': 5, 'а10': 2, '3': 2711, 'гб': 132, 'озу': 22, 'легкостью': 12, 'решает': 4, 'самые': 162, 'ресурсоемкие': 1, 'задачи': 22, 'позволяя': 5, 'насл

__Задание:__ реализуйте функцию, где тексту в соответствие ставится tf-idf вектор. 

In [0]:
def text_to_tfidf(text: str) -> np.array:
    """
    Возвращает вектор, где для каждого слова из словаря
    указан tf-idf
    """
    lent = len(text.split())

    a = text_to_bow(text, most_common)

    tf_idf = np.array([(a[i] / lent) * np.log(len(X_train) / docswterm[word]) for i, word in enumerate(most_common)])

    return tf_idf

In [0]:
print(__text_to_tfidf(preprocess("46, рублей, .. /")))

[0.1353933  0.12048274 0.         ... 0.         0.         0.        ]


__Задание:__ а теперь реализуйте функцию, которая преобразует наш датасет и для каждого объекта сопоставляет вектор tf-idf.

In [0]:
def items_to_tfidf(items: np.array) -> np.array:
    """ 
    Для каждого товара возвращает его tfidf вектор
    """
    #prep = text_to_tfidf([i[0] + ' ' + i[1] for i in items])
    tfidf = np.zeros([len(items), 10000])

    for i, row in enumerate(items):
      txt = items[i][0] + " " + items[i][1]
      tfidf[i] = text_to_tfidf(txt)

      if i % 1000 == 0:
        print(i)    

    return tfidf

In [0]:
print(items_to_tfidf(X_train[20000:]))

In [0]:
X_train_tfidf = items_to_tfidf(X_train)
X_test_tfidf = items_to_tfidf(X_test)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
0
1000
2000
3000
4000
5000
6000
7000
8000


In [0]:
print(X_train_tfidf[:2])

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.02780371 0.01110134 ... 0.         0.         0.        ]]


__Задание:__ обучите логистическую регрессию и SVC, оцените качество (accuracy_score)

In [0]:
# Your code here
lr_model = LogisticRegression(max_iter = 5000)
lr_model.fit(X_train_tfidf, y_train)

print(accuracy_score(lr_model.predict(X_test_tfidf), y_test))

0.6795555555555556


In [0]:
svc_model = LinearSVC(C = 0.1, max_iter = 10000)
svc_model.fit(X_train_tfidf, y_train)

print(accuracy_score(svc_model.predict(X_test_tfidf), y_test))

0.7271111111111112


### Hashing Vectorizer (1 балл)

Попробуйте использовать `sklearn.feature_extraction.text.HashingVectorizer` для векторизации текстов.
Обязательно оцените качество работы алгоритмов классификации с использованием новой векторизации.

In [0]:
# Your code here
from sklearn.feature_extraction.text import HashingVectorizer
vectorizer = HashingVectorizer(n_features=10000)

In [0]:
#vectorizer.fit_transform(X_train[5])

<2x1048576 sparse matrix of type '<class 'numpy.float64'>'
	with 60 stored elements in Compressed Sparse Row format>

In [0]:
X_train_h = np.array([X_train[i][0] + ' ' + X_train[i][1] for i in range(len(X_train))])
X_test_h = np.array([X_test[i][0] + ' ' + X_test[i][1] for i in range(len(X_test))])

In [0]:
X_train_h.shape

(21000,)

In [0]:
X_train_hash = vectorizer.fit_transform(X_train_h)
X_test_hash = vectorizer.transform(X_test_h)

In [0]:
X_train_hash

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
X_train_hash = X_train_hash.toarray()
X_test_hash = X_test_hash.toarray()

In [0]:
lr_model = LogisticRegression()
lr_model.fit(X_train_hash, y_train)

print(accuracy_score(lr_model.predict(X_test_hash), y_test))

C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vladimir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7127777777777777


In [0]:
svc_model = LinearSVC(C = 0.1, max_iter = 10000)
svc_model.fit(X_train_hash, y_train)

print(accuracy_score(svc_model.predict(X_test_hash), y_test))

0.7558888888888889


### Word Vectors (3 балла)

Давайте попробуем другой подход -- кажому слову сопоставим какой-то эмбеддинг (вектор).

Вектора будут небольшой размерности. Таким образом мы снизим количество параметров в модели.

Вектора мы возьмём уже готовые (обученные на текстах из интернета), так что наша модель будет знать некоторую дополнительную информацию о внешнем мире.

In [13]:
!wget https://www.dropbox.com/s/0x7oxso6x93efzj/ru.tar.gz

--2020-04-23 17:44:46--  https://www.dropbox.com/s/0x7oxso6x93efzj/ru.tar.gz
Resolving www.dropbox.com (www.dropbox.com)... 162.125.65.1, 2620:100:6021:1::a27d:4101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.65.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/0x7oxso6x93efzj/ru.tar.gz [following]
--2020-04-23 17:44:47--  https://www.dropbox.com/s/raw/0x7oxso6x93efzj/ru.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9bb04509085caac64ddeb79348.dl.dropboxusercontent.com/cd/0/inline/A2bkH0W-S_QEJBoVES31xAL-xQbhiBndLkyMh95vzlOuUQ_dfp8JqWLvFRK4tsR8zD5nNa9yLZSUcEv28I6u52dhloSjBnJFKAXyHPgZO4tfQA/file# [following]
--2020-04-23 17:44:47--  https://uc9bb04509085caac64ddeb79348.dl.dropboxusercontent.com/cd/0/inline/A2bkH0W-S_QEJBoVES31xAL-xQbhiBndLkyMh95vzlOuUQ_dfp8JqWLvFRK4tsR8zD5nNa9yLZSUcEv28I6u52dhloSjBnJFKAXyHPgZO4tfQA/file
Resolving uc9bb04509085ca

In [0]:
!tar -xzf ru.tar.gz

In [0]:
#pip install -U gensim

Requirement already up-to-date: gensim in c:\users\vladimir\anaconda3\lib\site-packages (3.8.2)
Note: you may need to restart the kernel to use updated packages.


In [0]:
import gensim
from gensim.models.wrappers import FastText

model = FastText.load_fasttext_format('ru.bin')

In [31]:
# как мы видим, каждому словву данная модель сопоставляет вектор размерности 300

print(model['привет'].shape)
print(model['привет'])

(300,)
[ 0.02916384  0.02167605  0.05127367 -0.00971958  0.0465235  -0.03945766
  0.02737866  0.00638128 -0.03774629 -0.04257201 -0.00995653  0.02291315
 -0.02301722  0.06697998 -0.03674482 -0.02403202 -0.05404469  0.01372932
  0.00926399 -0.0013149   0.11941359 -0.022448    0.04011497  0.06980549
  0.00407011 -0.09384539  0.03050164 -0.02578281 -0.03525181 -0.06603175
  0.04752798  0.05874675  0.01983666  0.06092105 -0.00957561  0.08307806
 -0.01288903  0.04705157  0.02198839 -0.00649013 -0.0171444   0.03302203
  0.02124882 -0.01902875 -0.05235172  0.03458685 -0.01409259 -0.07477519
  0.01916078  0.02985001  0.0086322   0.03051201  0.02831862  0.04549561
  0.00761138 -0.05459622  0.09056009 -0.08807947 -0.05420396 -0.04793203
 -0.05672329 -0.03025264 -0.03024072 -0.05890108 -0.03137474  0.03292617
  0.05440779 -0.04548327 -0.07266086 -0.09327219  0.07247883  0.0111061
  0.01824225 -0.10570452  0.05110046 -0.04659343 -0.03277056 -0.00803401
 -0.03978698  0.00826598 -0.01074128  0.01843

In [0]:
# Будем рассматривать эмбеддинг предложения, как сумму эмбеддингов токенов

def sentence_embedding(sentence: str) -> np.array:
    """
    Складывает вектора токенов строки sentence
    """
    tkns = tokenizer.tokenize(preprocess(sentence))
    emb = np.zeros(300)
    for token in tkns:
        if token in model:
            emb += model[token]

    return emb
    # your code here

In [33]:
sentence_embedding('сдаётся уютный , тёплый гараж для стартапов в ml')[::50]

array([ 0.08189847,  0.07249197, -0.15601223,  0.03782297,  0.09215296,
       -0.23092947])

In [0]:
assert np.allclose(sentence_embedding('сдаётся уютный , тёплый гараж для стартапов в ml')[::50],
                   np.array([ 0.08189847,  0.07249198, -0.15601222,  0.03782297,  0.09215296, -0.23092946]))

__Задание:__ сделайте все то же, что в предыдущих пунктах -- реализуйте функцию, которая преобразует данные, а затем обучите логистическую регрессию и SVM, оцените качество.

In [0]:
# a lot of your code here
def items_to_vectors(items: np.array) -> np.array:
    vcts = np.zeros((len(items), 300))

    for i, row in enumerate(items):
      txt = items[i][0] + " " + items[i][1]
      vcts[i] = sentence_embedding(txt)

      if i % 1000 == 0:
        print(i)


    return vcts

In [36]:
X_train_vect = items_to_vectors(X_train)
X_test_vect = items_to_vectors(X_test)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
0
1000
2000
3000
4000
5000
6000
7000
8000


In [41]:
X_train_vect[2]

array([-5.76031944e-01,  5.34498760e-01,  8.65831677e-01, -5.25400335e-01,
       -6.44728752e-01,  9.91655788e-01,  6.15278174e-01, -2.84768618e-01,
        3.16941176e-02,  2.79395385e+00, -7.15180357e-01,  1.13307631e+00,
        9.52309907e-02, -6.27957013e-01, -1.92104992e+00,  1.46688621e+00,
        4.64169879e-01,  2.18314643e+00,  1.05550356e-01,  1.58542860e+00,
       -1.08448756e-02, -1.00467436e+00,  2.14228727e+00, -8.86274591e-01,
        7.46207368e-01,  1.20604454e+00,  1.04137586e+00, -1.28678840e+00,
       -2.06944977e+00,  6.70885612e-01, -1.66915493e-02, -1.48687902e+00,
        1.12531464e+00,  1.20757944e+00,  7.85472836e-01, -5.37765195e-01,
        6.46002929e-01,  9.33610981e-01, -2.06723874e+00, -2.24552032e-01,
       -1.90690808e-01,  7.14898707e-01, -6.59619184e-01, -7.06159817e-01,
       -4.35744998e-01, -1.22284691e+00,  2.25487746e-01,  2.51638687e-01,
        1.20755407e+00,  1.41511958e-01,  5.77088078e-01,  8.71006521e-01,
       -6.27564913e-01, -

In [37]:
X_train_vect.shape

(21000, 300)

In [40]:
lr_model = LogisticRegression(max_iter = 5000)
lr_model.fit(X_train_vect, y_train)

print(accuracy_score(lr_model.predict(X_test_vect), y_test))

0.583


In [41]:
svc_model = LinearSVC(C = 0.1)
svc_model.fit(X_train_vect, y_train)

print(accuracy_score(svc_model.predict(X_test_vect), y_test))

0.5794444444444444


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


### Что дальше? (6 баллов)

Для получения максимальной оценки вам нужно решить любые 2 пункта. Решение каждого пункта даст вам полтора балла:

1. Реализовать N-Gram модели текстовой классификации (__1.5 балла__)

2. Поработать с другими эмбеддингами для слов (например word2vec или GloVe) (__1.5 балла__)

3. Другие способы токенизации (pymorphy2, spaCy) (__1.5 балла__)

4. Добиться качества > 0.765 на тестовых данных (попробуйте другие токенизаторы, предобработку текста, и любые другие идеи, которые вам придут в голову) (__1.5 балла__)

Снабжайте код пояснениями и графиками.
Обязательно необходимо написать вывод по каждому пункту, который вы реализуете.

In [0]:
# две строчки кода здесь

4. В одной из моделей выше https://colab.research.google.com/drive/1O3Yjz3MDqNkRcTEUKJzN8YHdQRQaJEB6#scrollTo=LHbeEIfxvbUq&line=2&uniqifier=1 (с включением title с определенным весом в bow) удалось добиться качества в 0.78+, что однако может являться следствием мультиколлинеарности и дуюлирования информации

